### ISSUE TITLE
Cannot Import Mechs

### ISSUE THREAD

**Issue by BlackCrusader** [Markemp/Cryengine-Importer#14]
I cannot import Marauder II.
When using old blender 2,7 it is missing weapons and the bones are detached.
In this version of Blender, for example I can properly import King Crab.

In newest version of Blender I get this error for both Marauder and King Crab:
![Capture](https://user-images.githubusercontent.com/85196620/121409937-55e54980-c962-11eb-84f3-92a4950974ad.PNG)

**Comment by Markemp** [comment]
This issue was fixed in the latest release (v2.0.6).  Can you download that version and try again?  Thanks!

https://github.com/Markemp/Cryengine-Importer/releases/latest

**Comment by BlackCrusader** [comment]
Yeah I am still getting that. I downloaded the latest version of your importer.
![Capture](https://user-images.githubusercontent.com/85196620/121782496-f5e0e400-cba9-11eb-8ef1-ac44291d5105.PNG)
![Capture7](https://user-images.githubusercontent.com/85196620/121782501-f8433e00-cba9-11eb-97dc-935ac424534c.PNG)

I did not try using it on Old blender version cause you said it is unsupported.

**Comment by BlackCrusader** [comment]
Do you need any specific log files?

I really wish to help resolve it.

Yea, actualy the more selfish reason is that I wanna 3D print the Marauder... :P

**Comment by Markemp** [comment]
It looks like you didn't extract all the game files?  Part of the directory structure is there should be a \Textures directory where the default material can be found.  According to the stack trace you posted, it's looking for a file in e:\depot\textures called default_mat_warning.dds.  Can you check to see if that file exists?  If not, be sure to grab **all** the game files and extract them.

**Comment by BlackCrusader** [comment]
It does not exist.
I only extracted marauderii.pak

Same as with King Crab.

In the old version, King crab is properly extracted with all the bones attached:
![Capture](https://user-images.githubusercontent.com/85196620/121790938-e7fc8480-cbe4-11eb-91e5-900b61c73395.PNG)

So I don't think it is an issue with the extracted files.

MarauderII also extracts in the old blender, however:
![Capture2](https://user-images.githubusercontent.com/85196620/121790968-2f831080-cbe5-11eb-8343-0b0a85392f9c.PNG)

It does not have the bones.

I am only having issue with the importer on the new blender for ALL mechs.

Extracting all of the game files will take a while... I will probably leave it overnight.

However, it would be good if the solution to extracting a single mech would be to extract only it's files:
![files 1](https://user-images.githubusercontent.com/85196620/121791028-c0f28280-cbe5-11eb-9b2d-4a926e284768.PNG)
![files 2](https://user-images.githubusercontent.com/85196620/121791030-c5b73680-cbe5-11eb-8d20-4007420596f3.PNG)

**Comment by BlackCrusader** [comment]
Can you try to replicate this error on your end by only extracting a single mech? And not extracting all of the game files?

**Comment by Markemp** [comment]
Hmm... I had an updated version that fixes this, but doesn't seem like I published it.  Whoops!

https://github.com/Markemp/Cryengine-Importer/releases/latest

Should be a 2.0.7 version now that will use an included texture file whenever it can't find one.  I don't have a similar set up to yours, so I can't test it properly, but please update your Blender add-on and let me know if this solves the issue.

**Comment by BlackCrusader** [comment]
It works!

However the release has too many stuff in it.

I extracted the whole "io_cryengine_importer" folder in to "*\Blender\2.92\scripts\addons"
![Capture](https://user-images.githubusercontent.com/85196620/121806113-df409880-cc4e-11eb-97aa-55a5204a8048.PNG)

The other archive "io_cryengine_importer.zip", seem redundand.

**Comment by Markemp** [comment]
You only need to download the io_cryengine_importer.zip file, not the whole project file. :)
